### ISSUE TITLE
Dont display Bank filler

### ISSUE THREAD

**Issue by Jilms** [Lazyfaith/runelite-bank-memory-plugin#1]
Could probably remove Bank fillers from displaying in the panel
![Screenshot_4](https://user-images.githubusercontent.com/36317465/97689023-5e42e100-1a71-11eb-8811-b1154d846f0e.png)

**Comment by Lazyfaith** [comment]
Good idea, will do. I don't ever use bank fillers so they didn't come to mind, thanks for bringing it up.

**Comment by Lazyfaith** [comment]
Fix should now be live!

**Comment by Jilms** [comment]
> Fix should now be live!

thanks :)
