### ISSUE TITLE
Is it possible to add an export option?

### ISSUE THREAD

**Issue by Budfraiz** [Lazyfaith/runelite-bank-memory-plugin#11]
Like export to excel or a notepad file?

**Comment by Lazyfaith** [comment]
What kind of format would you want the data in? Are you wanting it to be
exported for use in a program or to be something a human can read through
and understand?

**Comment by Budfraiz** [comment]
What I'm trying to do is make it easy for my GIM team to export their bank data as item names (not IDs) so I can easily check off what clue items they have on a shared spreadsheet. Do you have any suggestions?

**Comment by Onlymans** [comment]
Hey, I was looking for this feature as well and found this open issue.  

I think a csv format would be fine, nothing too fancy:
Item name, quantity, item ID

Btw, this plugin is amazing, thank you so much for creating it!

**Comment by Lazyfaith** [comment]
> Btw, this plugin is amazing, thank you so much for creating it!

Thanks!

> easy for my GIM team to export their bank data as item names (not IDs) so I can easily check off what clue items they have on a shared spreadsheet

The ideal solution would be something built into the plugin that talks to some server, and there's some process to selectively share your bank with friends or a group or something. It's not something I'm planning on doing right now though, if I ever do it. I think a good, easy enough thing for now would be an option when you right click a bank save to copy the data in CSV format to your clipboard.

I've seen some Google Sheets spreadsheets that can do some pretty cool stuff. I think you should be able to set one up so each of your players has 1 tab to paste their bank into, and then 1 main tab set up to automatically look at the individual banks for the items you want.

**Comment by Budfraiz** [comment]
Yes that would be a perfect solution for the time being. I have a spreadsheet setup with each player's clue items, they just don't want to sit there and tick each item off so if I can automate it for them it would work really well for us.

**Comment by Lazyfaith** [comment]
This should now be available in RuneLite!

You can export an item list to your clipboard via the action in the context menu. It can be found when you right click an item list you're currently viewing or by right clicking one of the banks in the saved banks list.

**Comment by Onlymans** [comment]
It works perfectly, you are awesome.  @Lazyfaith
