### ISSUE TITLE
Feature Request: Item tooltips

### ISSUE THREAD

**Issue by Fiffers** [Lazyfaith/runelite-bank-memory-plugin#13]
It'd be pretty useful to be able to hover over an item in your inventory and be able to see how many of that item remain in your bank. I'll probably put in a pull request for this once I have the time but wanted to gauge opinions beforehand.

**Comment by sjpfeiffer** [comment]
Got something working nicely! Took me a while to figure out how plugins work for runelite, as I haven't made one before, but it integrates nicely! Here's a preview:
![image](https://user-images.githubusercontent.com/14336807/169429602-b19ea568-f8d9-4c82-8fa4-4eab1d891ff3.png)

I may have made a mess, so I'm cleaning it up a bit before I submit a pull request. I'll have that PR close this comment while I'm at it.

**Comment by sjpfeiffer** [comment]
Also, I integrated a configuration menu as well. =)
![image](https://user-images.githubusercontent.com/14336807/169429813-48683602-0228-47c9-bdb8-584b918a4d0c.png)

**Comment by Lazyfaith** [comment]
Now been added and will be in v1.3! Thank you, Steven.
