### ISSUE TITLE
Jagex Launcher doesn't save "current bank" tab

### ISSUE THREAD

**Issue by joshbt44** [Lazyfaith/runelite-bank-memory-plugin#14]
I've used this plugin for the past year or so and it is one of my favorite plugins. When I open the bank it works fine, when I teleport away it tells me to login to a character. Only since I started using the jagex launcher.

**Comment by Raisoshi** [comment]
Having the same issue

**Comment by Olmium** [comment]
Experiencing the same

**Comment by Gollum69** [comment]
A temporary way around this is to access the bank, it'll populate all data in the 'Saved banks' tab for that character, and access all data that way. It does update it upon opening bank again too.

**Comment by Azrilkai** [comment]
any plans on updating / fixing this on a more permanent basis? the saved banks doesn't really cut it when you're doing more active gameplay and want to bank check constantly.

**Comment by Squimbert** [comment]
having the same issue.

**Comment by PidgeBirb** [comment]
Runelite's `client.getUsername()` is deprecated and now always returns an empty string. See [docs](https://static.runelite.net/api/runelite-api/net/runelite/api/Client.html#getUsername()). As a result, anytime the game state changes it won't be able to find the current save, since there's no username to look for, and it will empty the current bank panel.

Works fine for me if I update it to `client.getAccountHash()`. 

@Lazyfaith Are you still maintaining this repo?

**Comment by Squimbert** [comment]
> Runelite's `client.getUsername()` is deprecated and now always returns an empty string. See [docs](https://static.runelite.net/api/runelite-api/net/runelite/api/Client.html#getUsername()). As a result, anytime the game state changes it won't be able to find the current save, since there's no username to look for, and it will empty the current bank panel.
> 
> Works fine for me if I update it to `client.getAccountHash()`.
> 
> @Lazyfaith Are you still maintaining this repo?

How do I update it to client.getAccountHash()?

**Comment by Azrilkai** [comment]
> Runelite's `client.getUsername()` is deprecated and now always returns an empty string. See [docs](https://static.runelite.net/api/runelite-api/net/runelite/api/Client.html#getUsername()). As a result, anytime the game state changes it won't be able to find the current save, since there's no username to look for, and it will empty the current bank panel.
> 
> Works fine for me if I update it to `client.getAccountHash()`.

can you explain how we can accomplish this? please?

**Comment by Lazyfaith** [comment]
The fix has now been added and will be in v1.3. Submitting thise to RuneLite very soon.

**Comment by Lazyfaith** [comment]
The latest version has now been accepted by RuneLite so this should be fixed! Let me know if it's not.
