### ISSUE TITLE
Current bank Tab

### ISSUE THREAD

**Issue by GlMpsa** [Lazyfaith/runelite-bank-memory-plugin#16]
The plugin wont automaticly refresh the current bank. Sidepanel needs to be open for it to register the current bank into the plugin. I dont know if it's a problem with the plugin or is it just me doing something wrong.

**Comment by Squimbert** [comment]
i am also having the same issue.

**Comment by Lazyfaith** [comment]
I assume you're both using RuneLite via the Jagex Launcher with a Jagex account? Then this is the same as #14 and will be fixed very soon when the new plugin is pulled into Runelite.

**Comment by Lazyfaith** [comment]
The latest version has now been accepted by RuneLite so this should be fixed! Let me know if it's not.
