### ISSUE TITLE
WorldType enum change causes build fail

### ISSUE THREAD

**Issue by pystic-mizza** [Lazyfaith/runelite-bank-memory-plugin#5]
Hello, the Bank Memory plugin no longer builds with the latest RuneLite API changes to the `net.runelite.api.WorldType` enum. The application currently uses `WorldType.LEAGUE`, `WorldType.TOURNAMENT` and `WorldType.DEADMAN_TOURNAMENT` which no longer exist. See updated Enum doc: https://static.runelite.net/api/runelite-api/net/runelite/api/WorldType.html.

Here is the build failure stack trace: 

```
Cloning into '/tmp/pluginhub-package16370155590360153733/bank-memory/repo'...
HEAD is now at 5c6fdc6 Update version and README for v1.1.1
download: 1412ms
Dependency verification is an incubating feature.

> Task :compileJava FAILED
/tmp/pluginhub-package16370155590360153733/bank-memory/repo/src/main/java/com/bankmemory/data/BankWorldType.java:21: error: cannot find symbol
        if (worldsTypes.contains(WorldType.LEAGUE)) {
                                          ^
  symbol:   variable LEAGUE
  location: class WorldType
/tmp/pluginhub-package16370155590360153733/bank-memory/repo/src/main/java/com/bankmemory/data/BankWorldType.java:24: error: cannot find symbol
        if (worldsTypes.contains(WorldType.TOURNAMENT)) {
                                          ^
  symbol:   variable TOURNAMENT
  location: class WorldType
/tmp/pluginhub-package16370155590360153733/bank-memory/repo/src/main/java/com/bankmemory/data/BankWorldType.java:27: error: cannot find symbol
        if (worldsTypes.contains(WorldType.DEADMAN_TOURNAMENT)) {
                                          ^
  symbol:   variable DEADMAN_TOURNAMENT
  location: class WorldType
```

Source: https://github.com/runelite/plugin-hub/runs/3422606005#step:6:766

Do you think you could update the extension to properly utilize the updated WorldType Enum so that the extension becomes available on the Plugin Hub again?

Thanks a lot for this plugin by the way, it is very useful.

**Comment by Lazyfaith** [comment]
Hi there, I'm currently away on holiday so I won't be working on it for a little while. I hope to get on to it when I get back, some time a week (+) from now

**Comment by Septem151** [comment]
> Hi there, I'm currently away on holiday so I won't be working on it for a little while. I hope to get on to it when I get back, some time a week (+) from now

When you get the chance, I've submitted a PR #6 to fix this.

However, there's a slight problem (that can be addressed later on). You're using different world types for DMM, DMM tournament, and leagues, but the new net.runelite.WorldType enum only contains enums for TOURNAMENT_WORLD (which includes DMM tournaments), DEADMAN (which includes DMM), and SEASONAL (which contains both Leagues and Seasonal DMM). 

Therefore the "DEADMAN_TOURNAMENT" and "DEADMAN" BankWorldTypes will become the same, with one of them not being used anymore. Can't simply delete the BankWorldType enum for it because of this comment:

```java
// NB: changing these name will break automatic JSON deserialisation of existing saves
```

So for now, the PR just fixes the issue of building for the plugin hub, but the aforementioned is an issue that needs to be looked at further.

**Comment by Septem151** [comment]
Update: Was able to work around this by checking whether if the world type is both seasonal and deadman:
```java
public static BankWorldType forWorld(EnumSet<WorldType> worldTypes) {
    if (worldTypes.contains(WorldType.SEASONAL)) {
        return worldTypes.contains(WorldType.DEADMAN) ? BankWorldType.DEADMAN_TOURNAMENT : BankWorldType.LEAGUE;
    }
    if (worldTypes.contains(WorldType.TOURNAMENT_WORLD)) {
        return BankWorldType.TOURNAMENT;
    }
    if (worldTypes.contains(WorldType.DEADMAN)) {
        return BankWorldType.DEADMAN;
    }
    return BankWorldType.DEFAULT;
}
```

Huzzah!

**Comment by Lazyfaith** [comment]
Thank you @Septem151 for resolving this with the following commits:

c25b7c80d24bb8b42567222046db589e163eb8eb
1b55c45a6bc91c56b273a6aa2e6d7d6a00c89642
129f6fc6381349249a0dc0fc994bf270cfffaa69
