### ISSUE TITLE
Large number of `null` in list

### ISSUE THREAD

**Issue by gricey432** [Lazyfaith/runelite-bank-memory-plugin#9]
![image](https://user-images.githubusercontent.com/1611345/141781189-6241af65-ab91-448c-bdf6-6fae74bcb8a7.png)

**Comment by Lazyfaith** [comment]
I've seen other people get this but never gotten it myself. Can you please send me your bank list data so I can see how this looks in there? To find that data...

Find the directory  "C:\Users\<username>\.runelite\"
Your RuneLite "settings.properties" file should be in there
In that file, find the line that starts with "bankMemory.currentList="
Copy out the data to send to me (you can remove your login names/emails from it before sharing the data).

You can post it in here or DM me it on Discord if you don't want to post your bank items publicly (LazyFaith#9169 on Discord).

**Comment by gricey432** [comment]
Hmm yeah, I see what you mean.
It's now gone and there's nothing suspicious in my currentList itemData. I'll keep an eye out for it and report back if I find it again

**Comment by gricey432** [comment]
I've had it happen again on a smaller scale, just a couple of nulls near the end, they're showing up as `-1` in the `itemData`.

```
bankMemory.currentList=[{"id"\:redact,"worldType"\:"DEFAULT","dateTimeString"\:"21\:10\:21, 23 Nov 2021","userName"\:"redact","itemData"\:"1151,1,4310,1,4302,1,4304,1,4306,1,4298,1,4300,1,4308,1,428,1,426,1,1506,1,19697,1,19691,1,19695,1,19693,1,20706,1,20704,1,20708,1,7539,1,1381,1,1383,1,1385,1,1387,1,13121,1,3105,1,579,2,3097,1,7456,1,20714,1,2890,1,9733,1,11709,1,1061,2,1293,1,1478,1,841,1,1059,2,9005,1,26170,1,26176,1,26180,1,1171,1,1157,1,26182,1,1191,1,2952,1,589,1,1301,2,1331,1,1139,1,1101,1,35,1,837,1,11061,1,2961,4,7668,1,1729,1,2942,1,2912,1,4502,1,577,1,10498,1,1097,1,847,1,8880,1,8882,1063,1169,3,845,1,1133,1,22254,1,1005,2,853,1,857,1,13137,1,227,347,233,3,249,33,251,20,253,58,255,17,257,9,2998,6,209,5,211,18,213,4,3051,4,217,3,221,4,117,2,135,2,91,2,121,1,2428,1,181,1,225,3,183,1,2430,1,175,2,1975,3,3010,40,7409,1,5312,4,5286,1,5283,1,5294,13,5293,15,5314,5,21486,2,5284,4,5313,10,21488,3,5318,363,5104,4,5320,21,5307,154,5101,20,5099,9,5323,14,5319,100,5096,30,5324,66,5309,51,5103,16,5308,92,5306,120,5098,25,5322,4,5305,246,5321,5,5102,13,21490,1,5105,1,5311,10,5295,1,5299,1,5292,7,5100,16,22879,2,5291,13,5281,3,5097,18,5376,435,5386,32,5416,5,5406,5,5310,30,5106,2,5296,2,5297,3,1955,4,5458,5,5968,15,5282,2,5301,2,5302,1,1438,4,1444,2,1452,1,1448,2,1436,46,7936,123,25700,2,24942,1,4551,1,11339,1,4278,12,1533,1,1526,2,1901,1,24,1,675,1,676,2,670,2,668,1,294,1,1550,2,1985,1,4601,3,231,1,552,1,6754,1,7534,1,7535,1,28,1,32,1,2958,6,2963,1,7649,1,2402,2,10491,1,11340,1,9025,1,1534,1,6670,1,6188,1,25135,1,6654,1,6655,1,6656,1,25131,1,23318,1,6182,1,6181,1,1837,1,1835,1,3058,1,1833,1,3061,1,25133,1,6183,4,995,418081,556,974,555,65,557,104,554,1792,559,187,558,640,562,374,560,57,565,53,561,200,563,65,564,30,9075,1,566,23,1755,2,1609,4,1623,6,1607,19,1621,1,1605,5,1619,1,1603,8,1601,18,946,4,1735,1,303,1,1931,10,590,4,1275,1,25539,1,12012,148,442,7,453,16,444,719,449,6,1733,2,1734,99,1891,191,13454,1,1949,1,952,5,2355,34,2353,1,2357,52,8790,8,8013,4,8794,1,960,15,2347,14,1511,14,1521,9,1519,54,1517,519,6333,104,6332,120,1515,33,309,1,313,95,301,1,311,2,307,1,11323,1,353,1,335,19,341,3,331,17,359,17,377,194,363,2,371,22,333,21,361,80,379,16,33,1,314,731,52,563,53,127,1785,1,5075,11,2570,1,1923,18,1925,191,1929,3,1783,168,954,8,596,1,3211,17,13573,69,20718,215,1935,1,2313,4,4,1,21760,1,1823,5,299,38,3857,1,2462,1,1897,1,2003,1,1560,1,411,6,21662,1,23182,1,3516,1,19734,1,4251,1,13660,1,25527,126,4599,1,4600,1,11334,1,2552,1,434,11,1761,1,11074,22,9625,1,2007,1,19653,4,464,12,1951,1,2114,1,247,1,2102,1,4702,1,594,1,4537,1,10981,1,13448,2,13460,3,10972,1,2327,3,2323,1,1539,111,2976,1,1919,2,305,1,4820,10,4822,2,4821,4,401,2,3440,4,3422,2,1777,11,1741,15,983,1,1779,29,21555,54,886,2232,21341,6,237,1,1963,2,1643,13,1775,32,567,62,772,16,771,2,1590,1,4819,12,11194,63,11190,1,25635,1,25644,1,25676,116,2550,2,890,216,2558,1,43,22,1987,37,-1,0,13419,227,-1,0,"}]
```

**Comment by gricey432** [comment]
I've also found a reproduction! The nulls are added when you "release" bank placeholders. I think I managed to create so many the first time by releasing a whole tab.

**Comment by gricey432** [comment]
I'd love to contrib a patch for this if you wouldn't mind leaving the ticket for me, been wanting to look at how runelite plugins work anyway

**Comment by Lazyfaith** [comment]
That's great, thank you for coming back with this info.

The fix for this wouldn't really interact with the RuneLite APIs at all I don't think, you'd just be learning my code. I do have another small enhancement that I've been meaning to do for a while and would actually mean a bit of interaction with RuneLite's APIs so that may be better for you to do if you want to learn a bit more about RuneLite.

You're welcome to do this but if you'd like to try the other then take a look at issue #10 and then I'll do this one.

**Comment by Lazyfaith** [comment]
Fix should be be live.

**Comment by gricey432** [comment]
Sweet! Did you find out anything about why they're in the incoming stream to start with?

**Comment by Lazyfaith** [comment]
I didn't to be honest! I just went off what you said for fixing it. I assume it's probably something in the base game that the bank interface knows to just ignore, or perhaps something RuneLite accidentally introduces.
